### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by siveti3** [blaccerik/tft#2]
improted all libs cannot run ;/ any tips? discord or smth

**Comment by blaccerik** [comment]
Its most likely that your missing static data files from the riot website. I'll soon clean up the code and make it more user friendly

**Comment by siveti3** [comment]
Traceback (most recent call last):
  File "C:\Users\Siveti\Desktop\tft-master\predict.py", line 25, in <module>
    from predict.edit_data import EditData
  File "C:\Users\Siveti\Desktop\tft-master\predict.py", line 25, in <module>
    from predict.edit_data import EditData
ModuleNotFoundError: No module named 'predict.edit_data'; 'predict' is not a package

**Comment by siveti3** [comment]
File "C:\Users\Siveti\Desktop\dft-master\predict.py", line 32
    e.read("C:\Users\Siveti\Desktop\dft-master\data/champions.json")
                                                                   ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by siveti3** [comment]
where do i get these editdata files

**Comment by siveti3** [comment]
add me on discord siveti#9138 i can do smoe testing for ya
