### ISSUE TITLE
Installed all modules get this error.

### ISSUE THREAD

**Issue by ghost** [blaccerik/tft#4]
Traceback (most recent call last):
  File "predict.py", line 25, in <module>
    from predict.edit_data import EditData
  File "C:\Users\\Desktop\tft-master\predict.py", line 25, in <module>
    from predict.edit_data import EditData
ModuleNotFoundError: No module named 'predict.edit_data'; 'predict' is not a package

**Comment by blaccerik** [comment]
I guess you don't have python on your path

**Comment by BatturM** [comment]
No it's on my path. It doesn't work on any system I've tested it on.
